// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4WXj9FnCA_ih7W1_tDoa1jKJYUP45JE',
    appId: '1:535956556233:web:4b7a81ba50d49009428018',
    messagingSenderId: '535956556233',
    projectId: 'marketplace-c8c6f',
    authDomain: 'marketplace-c8c6f.firebaseapp.com',
    storageBucket: 'marketplace-c8c6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmNtrleP09lbxL5ITSS7tyWGbUab8OSjg',
    appId: '1:535956556233:android:5feef61b7d0621c3428018',
    messagingSenderId: '535956556233',
    projectId: 'marketplace-c8c6f',
    storageBucket: 'marketplace-c8c6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNguV3vX5IHMkNXgVf-WnO3VcBLi8vftI',
    appId: '1:535956556233:ios:00fc1078f8d9ae31428018',
    messagingSenderId: '535956556233',
    projectId: 'marketplace-c8c6f',
    storageBucket: 'marketplace-c8c6f.appspot.com',
    iosClientId: '535956556233-qmh91niviq9d2200sf71gjrnvm6vvc5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.carSpare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNguV3vX5IHMkNXgVf-WnO3VcBLi8vftI',
    appId: '1:535956556233:ios:16b5dfc89df1e837428018',
    messagingSenderId: '535956556233',
    projectId: 'marketplace-c8c6f',
    storageBucket: 'marketplace-c8c6f.appspot.com',
    iosClientId: '535956556233-2tmg3gg0n0857tndlov3mlu73uf4u07o.apps.googleusercontent.com',
    iosBundleId: 'com.example.carSpare.RunnerTests',
  );
}
